; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_extra_dirs = lib

lib_deps =
    https://github.com/Caza20/libtropic-platformio.git#develop
    baracodadailyhealthtech/mbedtls

; build_unflags =
;     -std=gnu++11
;     -std=gnu++14


build_flags =
    ; -std=gnu++17
    -DLT_PLATFORM=rpi_pico
    ; -DLT_CAL=mbedtls_v4
    ; -DLT_SILICON_REV=ABAB   ; or -DACAB 
    ; -DLT_CAL_TREZOR_CRYPTO ; mbedtls_v4
    ; -DLT_CAL_TREZOR_CRYPTO=ON
    ; -DLT_SH0_KEYS=eng_sample
    -I include
    -D MBEDTLS_CONFIG_FILE=\"mbedtls_custom_config.h\" # This tells mbedtls to use our custom configuration file.
    -D CMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY # This is needed to prevent CMake from trying to compile a shared library, which is not supported on the Pico.



