; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_extra_dirs = lib
build_flags =
    -DARDUINO_ARCH_RP2040
    -I include
	-I lib
    -DABAB   ; o -DACAB según tu chip TROPIC01
    -DLT_USE_TREZOR_CRYPTO
lib_deps =
    https://github.com/Caza20/libtropic-platformio.git#v1.0.0       ; version stable
